[package]
edition = "2021"
name = "track"
version = "0.1.0"

[dependencies]
csv = "1.1.6"
hashring = "0.3.0"
rust_decimal = { version="1.23", features = [ "serde-float", "serde-with-float" ] }
serde = { version="1.0.137", features = [ "derive" ] }
anyhow = "1.0"
